### ISSUE TITLE
Problem with teams / suggestion

### ISSUE THREAD

**Issue by TheIronMinerLv** [zDevelopers/UHPlugin#141]
Hello!

Right now the game won't start if even 1 player isn't in a team - there are errors in console.

I think this could be fixable really easy - could you implement a "Force team" command, which would add remaining players to random empty teams?

Thanks.

**Comment by Jenjeur** [comment]
Hello, first of all, when you post a new issue, please read the big bold "Guidelines for contributing", because, as stated in this file, you most open separate issues for a Problem and a Suggestion, it is very impractical for us to have both in the same issue.

Teams are not important, if you type /uh start, game will start, regardless of teams, so the problem does not come from that, it is likely that you simply forgot to generate spawnpoints.

Can you tell me which version of the game and version of the plugin you are using ?
Also, what errors are there in the console ?

**Comment by TheIronMinerLv** [comment]
Sorry for misleading information, let's say this will be as a problem report. Before I'll provide a detailed information, if the game is started with some players, that haven't choosed a team, everything will work? They will be moved automatically in teams or what?

I was using 1.8.8 paperspigot before and there was the same problem, recently I used newest 1.11 paperspigot and the problem occured again. And of course, I used newest development version of this plugin. (15th December build 389)

I generated the spawnpoints successfully and when I typed "/uh start slow:true" or even without slow mode, it stopped "responding", there were these errors in console: http://pastebin.com/bpH8SYbi

**Comment by AmauryCarrade** [comment]
>If the game is started with some players, that haven't choosed a team, everything will work? They will be moved automatically in teams or what?

Yes. When the game starts, each player out of any team is placed in a solo team with only him inside, and a random color if enabled in the configuration (enabled by default).
It's also this way the solo games works (in fact for solo games, technically each player is in a solo team).

>I generated the spawnpoints successfully and when I typed "/uh start slow:true" or even without slow mode, it stopped "responding", there were these errors in console: http://pastebin.com/bpH8SYbi

Thanks for that, with this I can work. I'll check that (it seems to be a bit strange to me but anyway, some bugs are).

**Comment by AmauryCarrade** [comment]
This should be fixed in the latest build (in a few minutes, so Jenkins can build the thing). You were on a very specific case, see the commit description if you're curious.
